// <auto-generated />
using System;
using BitMono.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BitMono.Web.MigrationService.Migrations
{
    [DbContext(typeof(CrackmesDbContext))]
    [Migration("20260627112501_AddReactions")]
    partial class AddReactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BitMono.Web.Data.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnonymousHandle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("CrackmeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpoiler")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("CrackmeId", "CreatedAt");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.Crackme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnonymousHandle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("AuthorDifficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("CommentReactionsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ContentType")
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentVerdict")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int>("DifficultyCount")
                        .HasColumnType("integer");

                    b.Property<int>("DifficultySum")
                        .HasColumnType("integer");

                    b.Property<string>("DotnetRuntime")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<long>("DownloadCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsBitMonoObfuscated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTakenDown")
                        .HasColumnType("boolean");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int>("Preset")
                        .HasColumnType("integer");

                    b.Property<string>("PublicModeratorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QualityCount")
                        .HasColumnType("integer");

                    b.Property<int>("QualitySum")
                        .HasColumnType("integer");

                    b.Property<bool>("ReactionsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("SolvedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TakedownReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("TakenDownAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TargetPlatform")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TermsAcceptanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploaderIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid?>("UploaderUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsBitMonoObfuscated");

                    b.HasIndex("Sha256");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TargetPlatform");

                    b.HasIndex("TermsAcceptanceId");

                    b.HasIndex("UploaderUserId");

                    b.HasIndex("Status", "PublishedAt");

                    b.ToTable("Crackmes");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.CrackmeTag", b =>
                {
                    b.Property<Guid>("CrackmeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CrackmeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CrackmeTags");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.ModerationReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CrackmeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsTakedown")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<string>("TakedownReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<int>("Verdict")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CrackmeId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Verdict");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("ModerationReviews");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CrackmeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("smallint");

                    b.Property<byte>("Quality")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoterIpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("VoterUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CrackmeId", "VoterIpHash")
                        .IsUnique()
                        .HasFilter("\"VoterIpHash\" IS NOT NULL");

                    b.HasIndex("CrackmeId", "VoterUserId")
                        .IsUnique()
                        .HasFilter("\"VoterUserId\" IS NOT NULL");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "TargetId");

                    b.HasIndex("TargetType", "TargetId", "UserId", "Emoji")
                        .IsUnique();

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CrackmeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<string>("ReporterIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid?>("ReporterUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CrackmeId");

                    b.HasIndex("IsResolved");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.Solution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnonymousHandle")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasMaxLength(40000)
                        .HasColumnType("character varying(40000)");

                    b.Property<Guid>("CrackmeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasAttachment")
                        .HasColumnType("boolean");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpvoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CrackmeId", "Status");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.TermsAcceptance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedAt");

                    b.ToTable("TermsAcceptances");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.Comment", b =>
                {
                    b.HasOne("BitMono.Web.Data.Entities.Crackme", "Crackme")
                        .WithMany("Comments")
                        .HasForeignKey("CrackmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitMono.Web.Data.Entities.Comment", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Crackme");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.Crackme", b =>
                {
                    b.HasOne("BitMono.Web.Data.Entities.TermsAcceptance", "TermsAcceptance")
                        .WithMany()
                        .HasForeignKey("TermsAcceptanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("BitMono.Web.Data.Entities.AppliedProtection", "ProtectionsApplied", b1 =>
                        {
                            b1.Property<Guid>("CrackmeId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("Enabled");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(60);

                            b1.HasKey("CrackmeId", "__synthesizedOrdinal");

                            b1.ToTable("Crackmes");

                            b1
                                .ToJson("ProtectionsApplied")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CrackmeId");
                        });

                    b.Navigation("ProtectionsApplied");

                    b.Navigation("TermsAcceptance");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.CrackmeTag", b =>
                {
                    b.HasOne("BitMono.Web.Data.Entities.Crackme", "Crackme")
                        .WithMany("Tags")
                        .HasForeignKey("CrackmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitMono.Web.Data.Entities.Tag", "Tag")
                        .WithMany("Crackmes")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crackme");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.ModerationReview", b =>
                {
                    b.HasOne("BitMono.Web.Data.Entities.Crackme", "Crackme")
                        .WithMany("Reviews")
                        .HasForeignKey("CrackmeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Crackme");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.Rating", b =>
                {
                    b.HasOne("BitMono.Web.Data.Entities.Crackme", "Crackme")
                        .WithMany("Ratings")
                        .HasForeignKey("CrackmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crackme");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.Report", b =>
                {
                    b.HasOne("BitMono.Web.Data.Entities.Crackme", "Crackme")
                        .WithMany()
                        .HasForeignKey("CrackmeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Crackme");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.Solution", b =>
                {
                    b.HasOne("BitMono.Web.Data.Entities.Crackme", "Crackme")
                        .WithMany("Solutions")
                        .HasForeignKey("CrackmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crackme");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.Crackme", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Ratings");

                    b.Navigation("Reviews");

                    b.Navigation("Solutions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("BitMono.Web.Data.Entities.Tag", b =>
                {
                    b.Navigation("Crackmes");
                });
#pragma warning restore 612, 618
        }
    }
}
